# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=64)),
                ('apartment_number', models.CharField(max_length=16, null=True)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('zipcode', models.CharField(max_length=5)),
                ('district', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LawMaker',
            fields=[
                ('title', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(max_length=32, null=True)),
                ('suffix', models.CharField(max_length=8, null=True)),
                ('gender', models.IntegerField(default=0)),
                ('party', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('senate_rank', models.CharField(max_length=6, null=True)),
                ('state', models.CharField(default=0, max_length=2)),
                ('religion', models.CharField(max_length=32, null=True)),
                ('district', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=64, null=True)),
                ('office', models.CharField(max_length=64, null=True)),
                ('rss_url', models.URLField(null=True)),
                ('contact_form', models.URLField(null=True)),
                ('url', models.URLField(null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('fax_number', models.CharField(max_length=12, null=True)),
                ('birthday', models.DateField(null=True)),
                ('bioguide_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('thomas_id', models.CharField(max_length=16, null=True)),
                ('govtrack_id', models.CharField(max_length=16, null=True)),
                ('opensecrets_id', models.CharField(max_length=16, null=True)),
                ('votesmart_id', models.CharField(max_length=16, null=True)),
                ('fec_id', models.CharField(max_length=16, null=True)),
                ('cspan_id', models.CharField(max_length=16, null=True)),
                ('maplight_id', models.CharField(max_length=16, null=True)),
                ('house_history_id', models.CharField(max_length=16, null=True)),
                ('icpsr_id', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(max_length=32)),
                ('salutation', models.CharField(max_length=8, null=True)),
                ('verified', models.IntegerField(default=0)),
                ('birthday', models.DateField(null=True)),
                ('race', models.IntegerField(default=0, null=True)),
                ('bio', models.CharField(default='', max_length=256)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('from_pop_up', models.CharField(max_length=32, null=True)),
                ('referral_hash', hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', blank=True, min_length=4, null=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='sporting_backend.Address')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SportingReferrals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('sign_ups', models.PositiveIntegerField(default=0)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sporting_referrals', to='sporting_backend.Profile')),
                ('referred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='sporting_backend.SportingReferrals')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='congress_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='congress_person', to='sporting_backend.LawMaker'),
        ),
        migrations.AddField(
            model_name='address',
            name='senator_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senator_1', to='sporting_backend.LawMaker'),
        ),
        migrations.AddField(
            model_name='address',
            name='senator_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senator_2', to='sporting_backend.LawMaker'),
        ),
    ]
